"""Control catalogs, the collector->control crosswalk, and coverage analysis."""

from __future__ import annotations

from dataclasses import dataclass, field
from functools import lru_cache
from importlib import resources
from typing import Any

import yaml

FRAMEWORKS = ("soc2", "iso27001", "nist_800_53", "fedramp_20x")
FRAMEWORK_LABELS = {
    "soc2": "SOC 2 (Trust Services Criteria)",
    "iso27001": "ISO/IEC 27001:2022 Annex A",
    "nist_800_53": "NIST SP 800-53 Rev. 5",
    "fedramp_20x": "FedRAMP 20x Key Security Indicators (Consolidated Rules 2026.09.13.02)",
}
FRAMEWORK_NOTES = {
    "fedramp_20x": (
        "KSIs are outcome statements, not controls. Which ones a provider must meet depends on "
        "its FedRAMP Certification Class, and FedRAMP's own validation process decides whether "
        "they are met. This table shows only where this tool's evidence is relevant."
    ),
}


def _load(name: str) -> Any:
    text = resources.files("grcevidence").joinpath(f"data/{name}").read_text(encoding="utf-8")
    return yaml.safe_load(text)


@lru_cache(maxsize=1)
def controls() -> dict[str, dict[str, dict[str, Any]]]:
    return _load("controls.yaml")


@lru_cache(maxsize=1)
def collector_map() -> dict[str, dict[str, list[str]]]:
    return _load("collector_map.yaml")


def controls_for(collector_id: str) -> dict[str, list[str]]:
    return {fw: list(ids) for fw, ids in collector_map().get(collector_id, {}).items()}


def validate_mapping(collector_ids: list[str] | None = None) -> list[str]:
    """Return a list of problems: unknown control ids, unmapped or stale collectors."""
    problems: list[str] = []
    cats = controls()
    for cid, by_fw in collector_map().items():
        for fw, ids in by_fw.items():
            if fw not in cats:
                problems.append(f"{cid}: unknown framework {fw!r}")
                continue
            for control in ids:
                if control not in cats[fw]:
                    problems.append(f"{cid}: {fw} control {control!r} is not in controls.yaml")
    if collector_ids is not None:
        mapped = set(collector_map())
        problems += [
            f"collector {c!r} has no entry in collector_map.yaml"
            for c in collector_ids
            if c not in mapped
        ]
        problems += [
            f"collector_map.yaml lists unknown collector {c!r}" for c in mapped - set(collector_ids)
        ]
    return problems


@dataclass
class ControlCoverage:
    control: str
    title: str
    type: str
    collectors: list[str] = field(default_factory=list)

    @property
    def automated(self) -> bool:
        return bool(self.collectors)


def coverage(framework: str) -> list[ControlCoverage]:
    """For each control in a framework, which collectors produce relevant evidence."""
    if framework not in FRAMEWORKS:
        raise ValueError(f"unknown framework {framework!r}; choose from {list(FRAMEWORKS)}")
    rows = {
        cid: ControlCoverage(cid, meta["title"], meta["type"])
        for cid, meta in controls()[framework].items()
    }
    for collector, by_fw in collector_map().items():
        for cid in by_fw.get(framework, []):
            if cid in rows:
                rows[cid].collectors.append(collector)
    return list(rows.values())


def coverage_markdown() -> str:
    """Human-readable crosswalk: which controls have automated evidence, which need manual evidence."""
    lines = [
        "# Control coverage",
        "",
        "Generated by `grc-evidence coverage --format markdown`. *Automated* means at least one",
        "collector produces configuration evidence relevant to the control; it does not mean the",
        "control is satisfied. *Manual* controls need policies, records or attestations that no",
        "cloud API can supply.",
        "",
    ]
    for fw in FRAMEWORKS:
        rows = coverage(fw)
        tech = [r for r in rows if r.type == "technical"]
        auto = [r for r in tech if r.automated]
        lines += [
            f"## {FRAMEWORK_LABELS[fw]}",
            "",
            f"{len(auto)} of {len(tech)} technical controls have automated evidence; "
            f"{len(rows) - len(tech)} organizational controls are outside what collectors can evidence.",
            "",
            *([FRAMEWORK_NOTES[fw], ""] if fw in FRAMEWORK_NOTES else []),
            "| Control | Title | Type | Automated evidence from |",
            "|---|---|---|---|",
        ]
        for r in rows:
            src = ", ".join(f"`{c}`" for c in r.collectors) if r.collectors else "-"
            kind = r.type if r.automated or r.type == "organizational" else "technical (gap)"
            lines.append(f"| {r.control} | {r.title} | {kind} | {src} |")
        lines.append("")
    return "\n".join(lines)


def collectors_markdown() -> str:
    """Reference table of every collector: scope, permissions and control mapping."""
    from grcevidence.collectors.base import load_all

    lines = [
        "# Collector reference",
        "",
        "Generated by `grc-evidence collectors --format markdown`.",
        "",
        "*Global* collectors run once per account; *regional* ones run once per configured region.",
        "",
        "| Collector | Scope | What it checks | SOC 2 | ISO 27001 | NIST 800-53 | FedRAMP 20x KSI | Permissions |",
        "|---|---|---|---|---|---|---|---|",
    ]
    for cid, cls in load_all().items():
        m = controls_for(cid)
        perms = "<br>".join(f"`{p}`" for p in cls.permissions)
        lines.append(
            f"| `{cid}` | {cls.scope} | {cls.title} | {', '.join(m.get('soc2', []))} | "
            f"{', '.join(m.get('iso27001', []))} | {', '.join(m.get('nist_800_53', []))} | "
            f"{', '.join(m.get('fedramp_20x', []))} | {perms} |"
        )
    return "\n".join(lines) + "\n"
